clang: Add clang macro check
This is to avoid the below issue, as local dev might be using GCC
instead of clang.

```
cilium/network_policy.cc:1218: error: ignoring '#pragma clang diagnostic' [-Werror=unknown-pragmas]
 1218 | #pragma clang diagnostic push
      |
cilium/network_policy.cc:1219: error: ignoring '#pragma clang diagnostic' [-Werror=unknown-pragmas]
 1219 | #pragma clang diagnostic ignored "-Wnull-dereference"
      |
cilium/network_policy.cc:1221: error: ignoring '#pragma clang diagnostic' [-Werror=unknown-pragmas]
 1221 | #pragma clang diagnostic pop
 ```