build: fix clang-tidy
Currenty the clang-tidy check fails with the following error due to
a missing direct include.

```
cilium/network_filter.cc:99:43: error: no header providing "absl::string_view" is directly included [misc-include-cleaner,-warnings-as-errors]
                                     absl::string_view sni, StreamInfo::StreamInfo& stream_info) {
```

This commit fixes this by adding the missing include.

Signed-off-by: Marco Hofstetter <marco.hofstetter@isovalent.com>