gha: Add ENVOY_MINOR_RELEASE for build task
This was missed in previous PR, hence there is failure in master branch.

Fixes: 5268dd06fa156599cc20ca509fa64313cb013c3e

```
ERROR: invalid tag "quay.io/cilium/cilium-envoy:-5268dd06fa156599cc20ca509fa64313cb013c3e": invalid reference format
```