bazel: Sync .bazelrc with upstream
Envoy requires to build with C++ versions at least C++14, this commit is
to set cxxopt=-std=c++17 as per upstream.

```
#0 8.995 external/com_google_absl/absl/base/policy_checks.h:79:2: error: "C++ versions less than C++14 are not supported."
#0 8.995 #error "C++ versions less than C++14 are not supported."
```